"""Object geometry the camera needs, taken from the brixzle CAD once and stored in ``model.json``.

Frames (all mm in the JSON, metres at runtime):
* brick: brixzle brick frame. Origin = footprint centre (x along the 2U length, y through the
  tine bores, z up); seated in the fixture or on the platform, the origin is ``origin_height`` above
  the floor. ``top`` is the top-surface height z(x, y) on a 1 mm grid.
* platform: the tower base strip, frame ``base0`` of the plan. Its footprint centre is at
  ``centre_x`` along its x axis; its frame origin (the seat level) is ``origin_height`` above the floor.
* fixture: the pick cradle; its slot frame is the seated brick's frame (footprint centred on it).
"""
import json
from functools import lru_cache
from pathlib import Path

import numpy as np

MODEL_PATH = Path(__file__).with_name('model.json')


def _profile_top(polygon, xs):
    from shapely.geometry import LineString
    out = []
    for x in xs:
        g = polygon.intersection(LineString([(x, -1e3), (x, 1e3)]))
        out.append(float(g.bounds[3]) if not g.is_empty else float('nan'))
    return out


DEFAULT_PARAMS = Path(__file__).resolve().parents[2]/'configs/ab.json'     # the A/B pair printed in stl_exports/2p5d_ab (V0 size, lean_mode ab)


def build_model(params_path=DEFAULT_PARAMS, part='A', grid_mm=1.0, samples=400_000, seed=0):
    """Compute ``model.json`` content from the brixzle CAD (needs CadQuery; run once)."""
    import trimesh
    from brixzle import cad, fixture as F, profile as pr, structures as S
    from brixzle.cli import load_params
    p = load_params(str(params_path))
    brick = cad.build_brick(p, part=part)
    lo, hi = brick['mesh'].bounds
    pts, _ = trimesh.sample.sample_surface(brick['mesh'], samples, seed=seed)
    nx, ny = int(round((hi[0] - lo[0])/grid_mm)), int(round((hi[1] - lo[1])/grid_mm))
    ix = np.clip(((pts[:, 0] - lo[0])/grid_mm).astype(int), 0, nx - 1)
    iy = np.clip(((pts[:, 1] - lo[1])/grid_mm).astype(int), 0, ny - 1)
    top = np.full((nx, ny), -np.inf)
    np.maximum.at(top, (ix, iy), pts[:, 2])
    missing = ~np.isfinite(top)
    if missing.any():   # fill the rare empty cell from its row
        for i, j in zip(*np.nonzero(missing)):
            row = top[i][np.isfinite(top[i])]
            top[i, j] = row.max() if row.size else hi[2]
    thickness = p.tooth_L + p.slot_extra + 4
    slot = F.slot_outer(p, F.FixtureParams())
    spec = S.tower(1).bases[0]           # the plan's base0 spans voxels [v0, v1) in its frame
    v0, v1 = spec[:2]
    base, _ = pr.base_outer(p, v1 - v0, thickness, spec[2] if len(spec) > 2 else 1)
    xs = np.arange(-50., 50. + 1e-9, grid_mm)
    return {
        '_comment': 'Generated by `testflight model` from the brixzle CAD; mm. Regenerate if the brick changes.',
        'params': Path(params_path).name, 'part': part,
        'brick': {'size': [float(hi[0] - lo[0]), float(hi[1] - lo[1])], 'origin_height': float(-slot.bounds[1]),
                  'top_x0': float(lo[0]), 'top_y0': float(lo[1]), 'grid': grid_mm,
                  'top': np.round(top, 2).tolist(), 'top_max': float(hi[2]), 'bottom': float(lo[2]),
                  'mass_g': float(brick['mass_g'])},
        'platform': {'size': [float(base.bounds[2] - base.bounds[0]), float(p.D)], 'centre_x': float((v0 + v1)/2*p.U),
                     'origin_height': float(thickness), 'profile_x': xs.tolist(),
                     'profile_top': _profile_top(base, xs + (base.bounds[0] + base.bounds[2])/2)},
        'fixture': {'size': [float(slot.bounds[2] - slot.bounds[0]), float(p.D)],
                    'origin_height': float(-slot.bounds[1]), 'profile_x': xs.tolist(),
                    'profile_top': _profile_top(slot, xs)},
    }


class Model:
    """``model.json`` in metres, with a brick top-height lookup."""

    def __init__(self, d):
        self.raw = d
        b, pl, fx = d['brick'], d['platform'], d['fixture']
        self.brick_size = np.array(b['size'])*1e-3
        self.brick_origin_height = b['origin_height']*1e-3
        self.brick_top_max = b['top_max']*1e-3
        self._top = np.array(b['top'])*1e-3
        self._top0 = np.array([b['top_x0'], b['top_y0']])*1e-3
        self._grid = b['grid']*1e-3
        self.platform_size = np.array(pl['size'])*1e-3
        self.platform_centre_x = pl['centre_x']*1e-3
        self.platform_origin_height = pl['origin_height']*1e-3
        self.platform_profile = (np.array(pl['profile_x'])*1e-3, np.array(pl['profile_top'])*1e-3)
        self.fixture_size = np.array(fx['size'])*1e-3
        self.fixture_origin_height = fx['origin_height']*1e-3
        self.fixture_profile = (np.array(fx['profile_x'])*1e-3, np.array(fx['profile_top'])*1e-3)

    def brick_top(self, x, y):
        """Top-surface height (m, brick frame) at brick-frame (x, y); NaN outside the footprint."""
        i = np.floor((np.asarray(x) - self._top0[0])/self._grid).astype(int)
        j = np.floor((np.asarray(y) - self._top0[1])/self._grid).astype(int)
        ok = (i >= 0) & (i < self._top.shape[0]) & (j >= 0) & (j < self._top.shape[1])
        out = np.full(np.shape(i), np.nan)
        out[ok] = self._top[i[ok], j[ok]]
        return out


@lru_cache(maxsize=4)
def _load(path):
    return Model(json.loads(Path(path).read_text()))


def load_model(path=None):
    return _load(str(path or MODEL_PATH))
